# Generated by Django 5.2 on 2025-04-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='file_type',
        ),
    ]
