# Generated by Django 5.2 on 2025-05-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_projectfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
