# Generated by Django 5.2 on 2025-05-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_projectfile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
