# Generated by Django 5.2 on 2025-05-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_projectfile_status_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fixtures',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store fixture configuration for the project'),
        ),
    ]
