# Generated by Django 5.2 on 2025-06-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ac_outdoor_units_location',
            field=models.CharField(blank=True, default='Back wall of the store', help_text='Location of AC outdoor units', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.TextField(blank=True, default='Shop No 1, Ground Floor, House No 3, Survey 390, 796, MG Road, Pune, Maharashtra', help_text='Enter the full address of the site', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='airport_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=9.5, help_text='Distance to nearest airport in KM', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='drainage_facility',
            field=models.BooleanField(default=False, help_text='Drainage facility available within premises'),
        ),
        migrations.AddField(
            model_name='project',
            name='electricity_load',
            field=models.DecimalField(blank=True, decimal_places=2, default=30, help_text='Electricity load capacity in KW', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='electricity_meter_location',
            field=models.CharField(blank=True, default='Basement Floor', help_text='Location of the electricity meter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='floor_level',
            field=models.CharField(blank=True, default='Ground floor', help_text='Specify the floor or level of the site', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hvac_system_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('cassette', 'Cassette'), ('split_ac', 'Split AC')], default='individual', help_text='Type of HVAC system', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_reference',
            field=models.CharField(blank=True, default='LKST212-MG road, Pune', help_text='Reference code or location name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='main_entrance_direction',
            field=models.CharField(blank=True, default='West', help_text='Direction of the main entrance', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nearest_airport',
            field=models.CharField(blank=True, default='Pune International Airport', help_text='Name of the nearest airport', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nearest_railway_station',
            field=models.CharField(blank=True, default='Pune Railway Station', help_text='Name of the nearest railway station', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='railway_station_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.2, help_text='Distance to nearest railway station in KM', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks or notes about the site', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_carpet_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=2186, help_text='Total carpet area in sq.ft.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='washroom',
            field=models.CharField(blank=True, default='Common washroom available', help_text='Washroom availability details', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='water_connection',
            field=models.BooleanField(default=False, help_text='Water connection available within premises'),
        ),
    ]
