# Generated by Django 5.2 on 2025-07-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sitemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='merch_mix_max',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store maximum merch mix configuration'),
        ),
        migrations.AddField(
            model_name='project',
            name='merch_mix_min',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store minimum merch mix configuration'),
        ),
    ]
