# Generated by Django 5.2 on 2025-08-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_project_merch_mix_max_project_merch_mix_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='room_measurements',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field to store room measurements with walls data'),
        ),
    ]
